_prog.run(lambda r,v: v.expecteq(r.exitcode, 56))
_prog.run(lambda r,v: v.expecteq(r.exitcode, 69), ['a'])
_prog.run(lambda r,v: v.expecteq(r.exitcode, 82), ['a', 'a'])
_prog.run(lambda r,v: v.expecteq(r.exitcode, 95), ['a', 'a', 'a'])
_prog.run(lambda r,v: v.expecteq(r.exitcode, 108), ['a', 'a', 'a', 'a'])
