_prog.run(lambda r,v: v.expecteq(r.exitcode, 129))
_prog.run(lambda r,v: v.expecteq(r.exitcode, 156), ['a'])
_prog.run(lambda r,v: v.expecteq(r.exitcode, 183), ['a', 'a'])
_prog.run(lambda r,v: v.expecteq(r.exitcode, 210), ['a', 'a', 'a'])
_prog.run(lambda r,v: v.expecteq(r.exitcode, 237), ['a', 'a', 'a', 'a'])
